
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/Programms_C++/cmake-3.29.0-windows-x86_64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
